---
# load_config task
#
- name: initialize function
  include_tasks: includes/init.yaml

- name: validate config_manager_text is defined
  fail:
    msg: "missing required arg: config_manager_text"
  when: config_manager_text is undefined

- name: load configuration into device
  cli_config:
    config: "{{ iosxr_config_text }}"
  vars:
    iosxr_config_text: "{{ config_manager_text }}"
